import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
// Permite especificar diretório de saída via variável de ambiente ou argumento
const outputDir = process.env.OUTPUT_DIR || process.argv[3] || 'src';
const outputFile = path.join(outputDir, 'main.js');

// Garantir que o diretório de saída exista
import fs from "fs";
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: outputFile,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}